### ISSUE TITLE
FragScape continually crashes after "launch selection"

### ISSUE THREAD

**Issue by Kiekoo** [MathieuChailloux/FragScape#17]
I've tried a few times now to use FragScape, but it keeps on crashing after I press "launch selection". It loads untill it reaches 66% and then does not continue any further.
I use QGIS 3.22.5, and all steps so far seem to go smoothly. Is there anything I can do about this issue?

**Comment by MathieuChailloux** [comment]
Hello,

Do you have an error message in log tab ?
You can activate debug mode in this tab to display more messages.

Regards,
Mathieu

**Comment by Kiekoo** [comment]
Thank you for your fast response! I did not get error messages, but I figured out I set the resolution too small which caused the crash. It works now!
