### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MikeSaCar** [MathieuChailloux/FragScape#3]
I report this error when executing. Could you help me to solve it please?
Traceback (most recent call last): File"C:/Users/MS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FragScape\algs\FragScape_algs.py", line 647, in processAlgorithm raise QgsProcessingException("Empty reporting area") _core.QgsProcessingException: Empty reporting area

**Comment by MathieuChailloux** [comment]
Hello,

This means that in your reporting layer you have a feature with an empty geometry.
If you still have troubles you can send me your data and configuration.

Best regards,
Mathieu

**Comment by MikeSaCar** [comment]
Hello,

Thank you very much for your time and support.

I am conducting a study in an agroecosystem, the idea is to generate the
FragScape analysis for the forest fragments that are in the surrounding
landscape (which is delimited by the layer called_ delimited_)
I have problems with identifying what my report layer should be, and if I
have a problem with geometries or layers in general. I appreciate your
help, thank you very much.

I attach the layers I work with

**Comment by MathieuChailloux** [comment]
Hello Mike,

Reporting layer should contain a polygon layer with study area.
I don't see any file attached, could you re-send it ? You can send it to fdrmc@free.fr directly.

Best regards,
Mathieu
