### ISSUE TITLE
Error: Algorithm FragScape:prepareLanduse not found

### ISSUE THREAD

**Issue by Fogel-ai** [MathieuChailloux/FragScape#5]
Hi,
I've been trying to execute the tool _FragScape_ on a agricultural land in a Swedish region, but I cannot get the second step to work. When I try to launch the selection in _2. Land Cover_, I get the following error message: 

> Algorithm FragScape:prepareLanduse not found 
![Error](https://user-images.githubusercontent.com/60700563/73914775-38115b80-48ba-11ea-9efa-41069715fdc4.PNG)

Does anyone know what is wrong and why the landuse is not found?

**Comment by MathieuChailloux** [comment]
Hi,
This means that FragScape has not been correctly installed (algorithms in toolbox are not available).
Try to uninstall FragScape, leave QGIS, relaunch QGIS, reinstall FragScape.

If error still occurs, I'll publish a new version (currently working on version 2.0).

Regards,
Mathieu

**Comment by Fogel-ai** [comment]
I tried with the un-/reinstallation and I still got the same error message. This was in QGIS 3.10.0. When I tried the tool with the same input data on QGIS 3.4.15, step 2 did not show any error. But when I tried the 3d step, I got this one:

> [warn] Failed to call prepareFragm : There were errors executing the algorithm.

> [warn] Failed to call buffer : There were errors executing the algorithm

**Comment by MathieuChailloux** [comment]
Okay, I'll try to dig in to understand issue with 3.10.0 (works fine on 3.10.1 on my computer but it could be for other reasons).

Could you activate debug mode (in log tab) and send me/display log messages before error message plz ?

**Comment by Fogel-ai** [comment]
![Error1](https://user-images.githubusercontent.com/60700563/73926287-b0cee280-48cf-11ea-9253-936cef71394e.PNG)
![Error2](https://user-images.githubusercontent.com/60700563/73926288-b0cee280-48cf-11ea-8711-e0136bb42310.PNG)
![Error3](https://user-images.githubusercontent.com/60700563/73926286-b0364c00-48cf-11ea-8432-7138a2705683.PNG)

**Comment by MathieuChailloux** [comment]
Seems like a problem of export from Shapefile to Geopackage.
Could you try to directly save your layer as a Geopackage (Export->Save Features as) or if this is no sensitive data just send me the layer and I'll check.

Regards,
Mathieu

**Comment by Fogel-ai** [comment]
It worked when I saved it in Geopackage format.
Thanks for all the help!

**Comment by Fogel-ai** [comment]
Hi again,
Unfortunately did a new problem occur in the fourth step when excecuting "Compute Metrics". This time all my files are in geopackage-format, but the following error message regarding the algorithm _qgis:clip_ pops up each time I excecute the tool
![Error1](https://user-images.githubusercontent.com/60700563/74224982-21a04100-4cba-11ea-8807-876c2ecc2144.PNG)
![Error2](https://user-images.githubusercontent.com/60700563/74224983-2238d780-4cba-11ea-9b78-50a181d9be62.PNG)

. Do you know why that is?

**Comment by MathieuChailloux** [comment]
Try to uncheck "Save intermediate layers" option.
This was a known issue in published version.

Next version shall be published in 2 weeks.

**Comment by Fogel-ai** [comment]
Yes, it seems to work. There is an error message:

> [user error] path does not exist : C:\Users\gushalru\Desktop\Fragmentation2\ResultFrag.zip

But I get a zipped result file that can be imported to QGIS (it does not load automatically).

**Comment by MathieuChailloux** [comment]
Is this output layer ?
It shall be a vector extension (.gpkg, .shp, ...)

**Comment by Fogel-ai** [comment]
Yes, my output is a file called _result.zip.gpkg_. It contains a vector layer with effective mesh size, splitting index, landscape division etc.

**Comment by MathieuChailloux** [comment]
Okayy, I would expect something like _result.gpkg_ without zip extension.
So the final results file has been well created ?

**Comment by Fogel-ai** [comment]
Yeah, it looks like the result in the user guide for the plugin
