### ISSUE TITLE
MeffVectorReport : Impossible to load source layer for INPUT

### ISSUE THREAD

**Issue by MathieuChailloux** [MathieuChailloux/FragScape#7]
Regression bug in 2.0

Algorithm MeffVectorReport fails when calling first sub-algorithm MeffVectorGlobal : invalid parameter for input.

**Comment by MathieuChailloux** [comment]
Fixed in 2.02

**Comment by XavierKoenig** [comment]
Bonjour Mathieu, 
Apres avoir suivi toutes les etapes du tutoriel sans probleme, quand j'arrive aux resultats j'obtiens cette erreur:

QgsProcessingException : Unable to execute algorithm Could not load source layer for INPUT: C:/Users/xavier/AppData/Local/Temp/processing_dxDudU/758eba9a8cb846da8fb3c984530fd67c/input_clipped.tif not found

Tous mes fichiers sont sur mon disque dur (Drive C), et j'ai re-installe le plugin a la version 2.0.6. 
Any advice? Merci par avance,
Xavier
